### ISSUE TITLE
Typo: column availible size hd

### ISSUE THREAD

**Issue by Rendol** [TheOrchid/Monitor#3]
![image](https://user-images.githubusercontent.com/2122240/34910429-bbbe7280-f8e7-11e7-815e-df980e1ba60d.png)

**Comment by tabuna** [comment]
Эм? Что не так?

**Comment by Rendol** [comment]
Доступно 92 из 101, а занято 96% - неувязочка)
По факту использовано 92.

**Comment by tabuna** [comment]
Возможно там проблема с 1000 vs 1024 и т.п.

**Comment by Rendol** [comment]
Доступно 92
Занято 96%

Должно быть:
Занято 92Gb
Занято 96%

**Comment by Rendol** [comment]
Опечатка же ж

**Comment by tabuna** [comment]
Обновил
